### PR TITLE
Update github.com/mdlayher/arp dependency to latest version

### PR DESCRIPTION
**Pull request by plant99**
### What?

This PR updates `github.com/mdlayher/arp` package to the [latest commit](https://github.com/mdlayher/arp/commit/6706a2966875c189c24afd003ffe801ff69542a1).

The command used is:

```
go get -u github.com/mdlayher/arp@6706a29
```

### Why?

As discussed in https://github.com/cilium/cilium/issues/25814, `arp` package should be upgraded to a new version.

### CODE REVIEW

**Comment by plant99** [comment]
@aanm could you please review this PR?

If I have understood the task correctly, the next steps would be:

1. To create a new release
2. To update `metallb`'s version in `cilium/cilium`

Please correct me if I'm wrong.

**Comment by aanm** [comment]
PTAL @dylandreimerink

**Comment by dylandreimerink** [comment]
I believe this breaks metallb. If I look at the diff of the arp package: https://github.com/mdlayher/arp/compare/f72070a231fc...6706a2966875

One of the changes is the move from `net.IP` to `netip.Addr` including in its public API. It is not a big deal when we update Cilium since we use `netip.Addr` everywhere already. But we will need to patch this metallb repo, because it will not compile in this state

**Review by dylandreimerink — CHANGES_REQUESTED** [review]
Checking out the repo and running tests results in:
```
go test ./...
# go.universe.tf/metallb/internal/layer2
internal/layer2/arp.go:52:49: cannot use ip (variable of type net.IP) as netip.Addr value in argument to arp.NewPacket
internal/layer2/arp.go:97:26: cannot use pkt.TargetIP (variable of type netip.Addr) as net.IP value in argument to a.announce
?       go.universe.tf/metallb/internal/allocator/k8salloc      [no test files]
?       go.universe.tf/metallb/internal/k8s     [no test files]
?       go.universe.tf/metallb/internal/logging [no test files]
?       go.universe.tf/metallb/internal/speakerlist     [no test files]
?       go.universe.tf/metallb/internal/version [no test files]
?       go.universe.tf/metallb/mirror-server    [no test files]
ok      go.universe.tf/metallb/controller       0.071s
ok      go.universe.tf/metallb/internal/allocator       0.004s
ok      go.universe.tf/metallb/internal/bgp     0.003s
ok      go.universe.tf/metallb/internal/config  0.005s
FAIL    go.universe.tf/metallb/internal/layer2 [build failed]
FAIL    go.universe.tf/metallb/speaker [build failed]
FAIL
```

**Comment by plant99** [comment]
Thanks for the context @dylandreimerink I'll send the fix soon.

**Comment by plant99** [comment]
@dylandreimerink  sorry for the delay, it's because of some personal reasons. I'll make sure to send some commits in the upcoming week.

**Comment by dylandreimerink** [comment]
> sorry for the delay

No need to apologize, finding time for OSS isn't always easy. Thank you for your continued effort!

**Comment by plant99** [comment]
@dylandreimerink thanks for your patience.

I've done the necessary changes for metallb to compile. Also, I had to refactor the test cases a little for it to work on my system. This could be a local issue, could you please check if the tests pass for you without the [latest commit](https://github.com/cilium/metallb/pull/12/commits/de4e1bee81aae21caf38ea54209f847ec34d193e)? In which case, I'll revert the same.

**Review by dylandreimerink — APPROVED** [review]
@plant99 thank you once again. Tests indeed pass for me locally, that last commit is also required for me.

**Comment by plant99** [comment]
@dylandreimerink Are there any next steps I can help with? Should I go ahead and update metallb's version in `cilium/cilium` and then create a revert PR for https://github.com/cilium/cilium/pull/25807 ?

**Pull request merged**
